include:
  - package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-raw-types: false
  errors:
    inference_failure_on_function_return_type: ignore
    inference_failure_on_untyped_parameter: ignore
    inference_failure_on_instance_creation: ignore
    inference_failure_on_function_invocation: ignore
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/generated/**"

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_returning_this: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    discarded_futures: false
    unawaited_futures: false
    avoid_dynamic_calls: false
