import 'dart:io' as io;

import 'package:drift/drift.dart';

import 'constructor.dart' if (dart.library.html) 'constructor_web.dart';
import 'daos.dart';
import 'tables.dart';
// FIXME: bug in modular generation? necessary for TaskState
import '../model/key_type.dart';
import '../model/protocol.dart';
import '../model/task.dart';

// auto-generated by drift_dev using
// dart run build_runner build
part 'database.g.dart';

@DriftDatabase(
  tables: [
    Devices,
    Users,
    Tasks,
    Groups,
    GroupMembers,
    Files,
    Challenges,
    Decrypts
  ],
  daos: [DeviceDao, UserDao, TaskDao],
)
class Database extends _$Database {
  static const fileName = 'db.sqlite';

  // TODO: Directory -> String?
  Database(io.Directory dir) : super(constructDatabase(dir.path, fileName));

  @override
  int get schemaVersion => 1;
}
